name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"





    - name: Clean and build with current version
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "🏗️ Building with version: $CURRENT_VERSION"
        rm -rf dist/
        bun run build
        echo "📦 Checking embedded version in built file:"
        grep -A2 -B2 "version.*:" dist/index.js | head -5 || echo "Version check failed"
      continue-on-error: true  # Continue even if existing TS errors

    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}