name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check for version bump commit
      run: |
        if git log --oneline -1 | grep -q "Bump version to"; then
          echo "Skipping release for version bump commit"
          exit 0
        fi
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Bump version
      run: npm version patch --no-git-tag-version

    - name: Get new version
      id: version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Commit version bump
      run: |
        git add package.json
        git commit -m "Bump version to ${{ steps.version.outputs.version }}"

    - name: Push commit
      run: git push

    - name: Create and push tag
      run: |
        git tag v${{ steps.version.outputs.version }}
        git push origin v${{ steps.version.outputs.version }}